### PR TITLE
Support code mods

### PR DESCRIPTION
**Pull request by yihleego**
## 1. ProjectXBootstrap.java (New)

Add `ProjectXBootstrap` to replace `ProjectXApp`, which is used to boot and load jar mods, such as replacing `deployment.properties` at runtime.

## 2. LauncherDigester.java (New)

Add `LauncherDigester` to modify `getdown.txt` and `digest.txt` before SK starts.

`getdown.txt`: 
```
...
# KnightLauncher resources
code = KnightLauncher.jar
class = com.lucasallegri.bootstrap.ProjectXBootstrap
client.class = com.lucasallegri.bootstrap.ProjectXBootstrap
```
`digest.txt`
```
...
KnightLauncher.jar = ...
digest.txt = ...
```

## 3. ModLoader.java (Modified)

It now reads the jar mods correctly

## 4. GameSettings.java (Modified)

[GameSettings.loadConnectionSettings()](https://github.com/lucasluqui/KnightLauncher/blob/c8f89ad085b3fa0ad481314861ad0341f779acf0/src/main/java/com/lucasallegri/launcher/settings/GameSettings.java#L73) is no longer used, it is replaced by [ProjectXBootstrap.loadConnectionSettings()](https://github.com/lucasluqui/KnightLauncher/blob/c8f89ad085b3fa0ad481314861ad0341f779acf0/src/main/java/com/lucasallegri/bootstrap/ProjectXBootstrap.java#L86).

https://github.com/lucasluqui/KnightLauncher/blob/c8f89ad085b3fa0ad481314861ad0341f779acf0/src/main/java/com/lucasallegri/bootstrap/ProjectXBootstrap.java#L86-L117

## 5. LauncherGlobals.java (Modified)

Modify `LauncherGlobals` to detect the jvm path and use `com.lucasallegri.bootstrap.ProjectXBootstrap` instead of `com.threerings.projectx.client.ProjectXApp`.

---

I tested it on Mac and Windows 10 (except Linux), both zip mods and jar mods work:
image

### CODE REVIEW

**Comment by lucasluqui** [comment]
Please wait for a bit. I will be reviewing this in the upcoming days and hopefully merging and testing for a later release.

**Comment by yihleego** [comment]
Currently `KL` is based on Java 8, so starting SK through `ProjectXBootstrap` requires the users' jvm to also be Java 8.

Do we need to split `ProjectXBootstrap` from `KL` project and compile with Java 5 or 6?

**Comment by Crowfunder** [comment]
What is the proposed code mod structure? It needs to be generalized and kept relatively simple to make creating such mods easier.

**Comment by yihleego** [comment]
> What is the proposed code mod structure? It needs to be generalized and kept relatively simple to make creating such mods easier.

Making code mods requires proficiency in Java, developers need to read the client code, and then try to modify the code. So I think the hardest thing is reading the code.

I don't have a best standard project layout, I am waiting for @lucasluqui to design one. 
Or you can design one yourself, KL will not limit it in my opinion.

See also [mods I made](https://github.com/spiralstudio/mods).

**Comment by The-File** [comment]
Code mods might be required for running the latest JVM as well, depending on how you launch projectx.

Trying to use default getdown, you'll need to block "jvmarg = -XX:+AggressiveOpts" from being set, this can be done with a simple code mod. Of course, you could also just ship your own getdown build and do it there.

You'll also need to swap out native libs for LWJGL with their latest 2.9.X variant, for compatibility purposes.

You'll also need to specify "--add-opens=java.*****=ALL-UNNAMED" type arguments for every single internal JDK API used for Java 16+.

That said, Java 20 is possible and runs SK perfectly fine:

image

**Comment by The-File** [comment]
That said, there should still be modifications put in place to allow the option of running the latest Java, even if you don't install or provide such,

**Comment by lucasluqui** [comment]
Code mods are not a requirement for Java 8+ VMs to function. I won't merge or implement any VM compatibility specific modifications into KL or the proposed code mods functionality by leego for the reason I detailed above.

Users that really want to go the extra mile are free to do so just not through KL.

**Comment by The-File** [comment]
...and with that said, that's why it was brought up in this thread, as it would be a use case for code modding.

**Comment by The-File** [comment]
Getdown code modification found to be unnecessary for running bleeding edge Java.

As per https://github.com/The-File/SK-Fixed/issues/2

**Comment by The-File** [comment]
ProjectXBootstrap.java is dependent on the version of spiral knights being utilized.

Specifically because the game client uses ProGuard obfuscation for method/class/field/etc obfuscation. The smallest change to an irrelevant part of the client will cause the obfuscator in the build script to be run again and thus create class files that are mutable even with no functional changes.

**Comment by The-File** [comment]
You'd need to resolve for fields/methods/class names dynamically rather than in source code.

**Comment by The-File** [comment]
In other words, if Spiral Knights ever updates in the future due to a one line change in the client to a part knight launcher nor code mods touch, nor should care about, ProjectXBootstrap.java would likely fail to work.

**Pull request merged**
